name: Build Android (dev branch)

on:
  workflow_dispatch
  

jobs:
  build:
    runs-on: ubuntu-latest # Or macos-latest if you prefer macOS for building

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Or 'zulu', 'adopt' etc.
        java-version: '17' # Flutter typically uses Java 11 or 17

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32' # Specify your Flutter version (e.g., '3.22.0')
        channel: 'stable' # Or 'beta', 'dev'

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Android App Bundle (AAB)
      run: flutter build appbundle --release

    - name: Upload App Bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned-aab
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Build Android APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned-apk
        path: build/app/outputs/flutter-apk/app-release.apk
